version: '3.8'

services:
  taskmanager:
    container_name: taskmanager_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver_db;Database=TaskManagementDB;User Id=sa;Password=YourPassword123;TrustServerCertificate=True;
    depends_on:
      - sqlserver_db

  sqlserver_db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sqlserver_db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourPassword123"
      ACCEPT_EULA: "Y"
